# Haveno App extends the features of Haveno, supporting mobile devices and more.
# Copyright (C) 2024 Kewbit (https://kewbit.org)
# Source Code: https://git.haveno.com/haveno/haveno-app.git
#
# Author: Kewbit
#    Website: https://kewbit.org
#    Contact Email: me@kewbit.org
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: haveno_app
description: "Haveno Multi-Platform Application"
license: AGPL-3
repository: https://git.haveno.com/haveno/haveno-app

authors:
  - Kewbit
publish_to: 'none'

version: 0.3.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  git: ^2.3.0 
  haveno: ^3.0.1
  socks5_proxy: ^1.0.6
  flutter_socks_proxy: ^0.0.3
  provider: ^6.0.0
  path_provider: ^2.1.4
  multi_select_flutter: ^4.1.3
  uuid: ^4.4.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  fixnum: ^1.1.0
  intl: ^0.19.0
  badges: ^3.1.2
  cryptography: ^2.7.0
  file: ^7.0.0
  path: ^1.9.0
  http2: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^1.0.0
  url_launcher: ^6.3.0
  archive: ^3.6.1
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.1
  interactive_chart: ^0.3.5
  chatview: ^2.1.1
  #local_auth: ^2.3.0 ## To do faceid etc
  package_info_plus: ^8.0.2
  #workmanager: ^0.5.2  ## Probably needed for ios to check for messafes every 15 mins
  flutter_background_service: ^5.0.7
  flutter_local_notifications: ^18.0.1
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  timezone: ^0.9.4
  crypto: ^3.0.5
  pointycastle: ^3.9.1
  onboarding: ^4.0.2
  collection: ^1.18.0
  dropdown_search: ^5.0.5
  http: ^1.2.2
  sentry_flutter: ^8.8.0
  shared_preferences: ^2.3.2
  sqlite3_flutter_libs: ^0.5.24
  tray_manager: ^0.2.4
  background_downloader: ^8.7.1
  #window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter_icons:
  android: true
  ios:
    generate: true
    image_path: "assets/icon/app_icon_smaller.png"
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/versions.json
    - assets/config/default/torrc
    - assets/getting-started-logo.png
    - assets/arbitration-logo.png
    - assets/haveno-logo.png
    - assets/tor-logo.png
    - assets/icon/app_icon.png
    - assets/icon/app_icon.ico
    - assets/icon/app_icon_smaller.png